language: node_js
sudo: false
node_js:
  - "unstable"
  - "stable"
  - "11.0"
  - "10.0"
  - "9.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
